(defn conn-cb [asc e a] (println (if e e "connected")))
(def conn (client/connect nil "127.0.0.1" 8087 conn-cb))
(def b (conv/byte-string<-utf8-string "B-56"))

(def k (conv/byte-string<-utf8-string "K01"))
(def v {:value (conv/byte-string<-utf8-string "V01")})
(object/put conn b k v {} result-cb)
(def k (conv/byte-string<-utf8-string "K02"))
(def v {:value (conv/byte-string<-utf8-string "V02")})
(object/put conn b k v {} result-cb)
(def k (conv/byte-string<-utf8-string "K03"))
(def v {:value (conv/byte-string<-utf8-string "V03")})
(object/put conn b k v {} result-cb)

(bucket/list conn b {} result-cb stream-cb)
(pprint (map conv/utf8-string<-byte-string @stream-result))
